### ISSUE TITLE
Просит обновиться

### ISSUE THREAD

**Issue by kikuok** [Eject37/ReTube#1]
Привет, скрипт выплёвывает при каждом обновлении страницы ютуба плашку, что обнови, дескать, меня. Категорически не желаю этого делать. Полез в настройки,выключил галку "спрашивать об обновлении". В итоге ничего не изменилось. Перезапускал всё и т.д., но бестолку. Как, чего может мне самому в коде найти эту запись и обрубить требование?

**Comment by Eject37** [comment]
Привет.
Можно вручную удалить эти строчки из кода для отключения проверки обновлений.
![image](https://github.com/Eject37/ReTube/assets/57284098/506911a6-a334-4e0a-a276-2893f9cc436c)

Также, в следующей версии, добавлю возможность выключить проверку обновлений.
