### ISSUE TITLE
 Баг с дизлайками

### ISSUE THREAD

**Issue by Etheresk** [Eject37/ReTube#2]
Я заметил, что дизлайки прогружаются только после загрузки страницы и **секции комментариев** (ввод, кол-во, сортировка, сами комментарии), и из-за этого:
- дизлайки не появляются если видео по-умолчанию открывается в широкоформатном режиме -> секция комментариев не прогружается -> дизлайки не прогружаются (но это только у меня на 2к мониторе, мб на других по другому)
- сама секция лайки/дизлайки убирает кол-во дизлайков при взаимодействии с ней, т.к. нету ре-рендера после ютубовского ре-рендера, хотя hover на дизлайке показывает их кол-во

**Comment by Eject37** [comment]
Спасибо, исправлено
