### ISSUE TITLE
Баг с эмбедами и подсказкой

### ISSUE THREAD

**Issue by Etheresk** [Eject37/ReTube#3]
Не знаю баг ли это, но странно, что самая первая подсказка триггерится на `YouTube Embed` видео вообще на любом сайте помимо самого `YouTube` (только первый раз после установки скрипта).

Плюс этот `embed` просто черный и не кликабельный, пока висит подсказка.

(Ну и еще маленькие ошибки в подсказке: "Что-бы открыть меню настроек, нажмите F2 находясь на сайте ютуба." -> "Чтобы открыть меню настроек, нажмите F2, находясь на сайте ютуба.")
![image](https://github.com/Eject37/ReTube/assets/73643707/e4f3afe3-14a0-4c78-8be3-4cf4f0e1445c)

**Comment by Eject37** [comment]
Спасибо, исправлено в [v4.2.7](https://github.com/Eject37/ReTube/releases/tag/v4.2.7)
