### ISSUE TITLE
Форматирование дизлайков

### ISSUE THREAD

**Issue by Noktomezo** [Eject37/ReTube#5]
Вернуть/добавить форматирование дизлайкам начиная с 1100, как у лайков. Примеры:

Сейчас
![image](https://github.com/user-attachments/assets/9c1d0840-e161-4bc0-a958-a9f8e54f4df5)
![image](https://github.com/user-attachments/assets/3c8c9cd5-73df-4747-9ca5-131fdcbe2697)

Должно быть (поправил через код элемента):
![image](https://github.com/user-attachments/assets/2c938ee8-e65e-47a2-aaa7-d75046bebe3b)
![image](https://github.com/user-attachments/assets/9476095d-45d0-4892-96d6-89233cad93ac)

Основываясь на округлении лайков округляется по следующему принципу:
`1_000`—`1_099` => `1 тыс.`
`1_100`—`9_999` => `1,1 тыс.`—`9,9 тыс.` (добавляется `float`)
`10_000`—`999_999` => `10 тыс.`—`999 тыс.`

Ну и также для:
`миллионов` => `млн`
`миллиардов` => `млрд` (хотя маловероятно, что такое видео найдется).
(точка после `млн` и `млрд` не добавляется т.к. это не сокращение в отличие от `тысяча` => `тыс.`)

`P.S.` Проверял на [этом](https://youtu.be/Kbk9BiPhm7o) и на [этом](https://youtu.be/UPrkC1LdlLY) видео

**Comment by Eject37** [comment]
Добавил форматирование в [v4.3.2](https://github.com/Eject37/ReTube/releases/tag/v4.3.2)
