### ISSUE TITLE
linux steamdeck

### ISSUE THREAD

**Issue by kotovasia5120** [Eject37/ReTube#6]
использую на стимдек и оформление не меняется![image](https://github.com/user-attachments/assets/2c4efadd-6ddf-4a77-9a55-3ae9f82b40ff)

**Comment by Eject37** [comment]
Визуальное оформление ReTube не работает на светлой версии YouTube

**Comment by kotovasia5120** [comment]
> Визуальное оформление ReTube не работает на светлой версии YouTube
Спасибо.
Привык что всегда  в системе темная  стояла.
